Repository We-re-WeRe/WeRe-Client, pull requests merged in 2024-05, with the labels that each got.

#58 FEAT: WebtoonInfo 페이지 하단 부분 (Contents) 구현
  were-client/src/components/atoms/IconButton/index.tsx
  were-client/src/components/atoms/ProfileButton/index.module.scss
  were-client/src/components/atoms/ProfileButton/index.tsx
  were-client/src/components/atoms/TextButton/index.module.scss
  were-client/src/components/atoms/TextButton/index.tsx
  were-client/src/components/molecules/ReviewCard/index.module.scss
  were-client/src/components/molecules/ReviewCard/index.tsx
  were-client/src/components/molecules/StorageBox/index.module.scss
  were-client/src/components/molecules/StorageBox/index.tsx
  were-client/src/components/molecules/WebtoonInfoDescription/index.module.scss
  were-client/src/components/molecules/WebtoonInfoUserItems/index.module.scss
  were-client/src/components/molecules/WebtoonInfoUserItems/index.tsx
  were-client/src/components/organism/WebtoonInfo/index.module.scss
  were-client/src/components/organism/WebtoonInfo/index.tsx
  were-client/src/components/organism/WebtoonInfoContent/index.module.scss
  were-client/src/components/organism/WebtoonInfoContent/index.tsx
  were-client/src/components/organism/WebtoonInfoReviews/index.module.scss
  were-client/src/components/organism/WebtoonInfoReviews/index.tsx
  were-client/src/components/organism/WebtoonInfoStorageList/index.module.scss
  were-client/src/components/organism/WebtoonInfoStorageList/index.tsx
  were-client/src/styles/_base.scss
Labels: enhancement

#59 FEAT: MyPage 하단 컨텐츠 구현 및 전체적인 스타일 조정
  were-client/public/assets/index.ts
  were-client/public/assets/private.svg
  were-client/public/assets/public.svg
  were-client/src/components/atoms/InputTable/index.module.scss
  were-client/src/components/atoms/InputTable/index.tsx
  were-client/src/components/atoms/TextButton/index.module.scss
  were-client/src/components/atoms/TextButton/index.tsx
  were-client/src/components/molecules/CategoryTitle/index.module.scss
  were-client/src/components/molecules/FollowingProfileBox/index.module.scss
  were-client/src/components/molecules/FollowingProfileBox/index.tsx
  were-client/src/components/molecules/IconText/index.tsx
  were-client/src/components/molecules/MyPageCategoryTitle/index.module.scss
  were-client/src/components/molecules/MyPageCategoryTitle/index.tsx
  were-client/src/components/molecules/ReviewBox/index.module.scss
  were-client/src/components/molecules/ReviewBox/index.tsx
  were-client/src/components/molecules/SmallProfileBox/index.module.scss
  were-client/src/components/molecules/SmallProfileBox/index.tsx
  were-client/src/components/molecules/WebtoonBox/index.module.scss
  were-client/src/components/molecules/WebtoonBox/index.tsx
  were-client/src/components/organism/FollowingList/index.module.scss
  were-client/src/components/organism/FollowingList/index.tsx
  were-client/src/components/organism/MyPageUnderContents/index.module.scss
  were-client/src/components/organism/MyPageUnderContents/index.tsx
  were-client/src/components/organism/NewStorageModal/index.module.scss
  were-client/src/components/organism/NewStorageModal/index.tsx
  were-client/src/components/organism/NewStorageModal/useNewStorageModal.tsx
  were-client/src/components/organism/ReviewBoxList/index.module.scss
  were-client/src/components/organism/ReviewBoxList/index.tsx
  were-client/src/components/organism/ReviewModal/index.tsx
  were-client/src/components/organism/StorageBoxList/index.module.scss
  were-client/src/components/organism/StorageBoxList/index.tsx
  were-client/src/components/organism/UserpageReviews/index.module.scss
  were-client/src/components/organism/UserpageReviews/index.tsx
  were-client/src/components/organism/UserpageStorages/index.module.scss
  were-client/src/components/organism/UserpageStorages/index.tsx
  were-client/src/styles/_base.scss
Labels: enhancement, fix

#60 FEAT: types 추가
  were-client/.eslintrc.json
  were-client/src/types/point.d.ts
  were-client/src/types/review.d.ts
  were-client/src/types/storage.d.ts
  were-client/src/types/tag.d.ts
  were-client/src/types/user.d.ts
  were-client/src/types/webtoon.d.ts
Labels: enhancement

#62 FEAT: ReviewCard 기능 추가 구현
  were-client/public/assets/index.ts
  were-client/public/assets/shortcut.svg
  were-client/src/components/atoms/IconButton/index.tsx
  were-client/src/components/atoms/WebtoonTag/index.tsx
  were-client/src/components/molecules/ReviewCard/index.module.scss
  were-client/src/components/molecules/ReviewCard/index.tsx
  were-client/src/components/molecules/StorageInfo/index.tsx
  were-client/src/components/molecules/TagList/index.module.scss
  were-client/src/components/molecules/TagList/index.tsx
  were-client/src/components/molecules/WebtoonInfoDescription/index.tsx
  were-client/src/components/organism/MyPageUnderContents/index.tsx
  were-client/src/components/organism/NewStorageModal/index.tsx
  were-client/src/components/organism/ReviewBoxList/index.tsx
  were-client/src/components/organism/ReviewCardList/index.module.scss
  were-client/src/components/organism/ReviewCardList/index.tsx
  were-client/src/components/organism/ReviewModal/index.tsx
  were-client/src/components/organism/WebtoonCategory/index.tsx
Labels: enhancement, fix

#64 FIX: Userpage 하단 컨텐츠 수정
  were-client/src/components/molecules/ReviewBox/index.module.scss
  were-client/src/components/molecules/ReviewBox/index.tsx
  were-client/src/components/organism/ReviewCardList/index.module.scss
  were-client/src/components/organism/UserpageReviews/index.module.scss
  were-client/src/components/organism/UserpageReviews/index.tsx
  were-client/src/components/organism/UserpageStorages/index.module.scss
  were-client/src/components/organism/UserpageStorages/index.tsx
  were-client/src/components/organism/UserpageUnderContents/index.module.scss
  were-client/src/components/organism/UserpageUnderContents/index.tsx
Labels: fix

#69 FIX: 마이페이지 오류 수정
  were-client/src/components/molecules/MyPageCategoryTitle/index.tsx
  were-client/src/components/organism/MyPageUnderContents/index.tsx
  were-client/src/components/organism/StorageBoxList/index.tsx
Labels: fix

#67 FEAT: MyPage 상단 컨텐츠 구현
  were-client/public/assets/edit.svg
  were-client/public/assets/index.ts
  were-client/src/components/atoms/IconButton/index.tsx
  were-client/src/components/atoms/ProfileButton/index.tsx
  were-client/src/components/molecules/LimitedInput/index.tsx
  were-client/src/components/molecules/ProfileBox/index.module.scss
  were-client/src/components/molecules/ProfileBox/index.tsx
  were-client/src/components/organism/MyPageTopContents/index.module.scss
  were-client/src/components/organism/MyPageTopContents/index.tsx
Labels: enhancement

#70 FEAT: Header Component 구현
  were-client/public/assets/index.ts
  were-client/public/assets/logout.svg
  were-client/public/assets/search.svg
  were-client/public/assets/user.svg
  were-client/src/components/atoms/IconButton/index.tsx
  were-client/src/components/atoms/InputTable/index.tsx
  were-client/src/components/atoms/ProfileButton/index.module.scss
  were-client/src/components/atoms/ProfileButton/index.tsx
  were-client/src/components/molecules/IconText/index.tsx
  were-client/src/components/molecules/NavigationBar/index.module.scss
  were-client/src/components/molecules/NavigationBar/index.tsx
  were-client/src/components/molecules/ProfilePopup/PopupBox.tsx
  were-client/src/components/molecules/ProfilePopup/index.module.scss
  were-client/src/components/molecules/ProfilePopup/index.tsx
  were-client/src/components/molecules/SearchBar/index.module.scss
  were-client/src/components/molecules/SearchBar/index.tsx
  were-client/src/components/molecules/WebtoonPopup/PopupBox.tsx
  were-client/src/components/molecules/WebtoonPopup/index.tsx
  were-client/src/components/organism/Layout/Header/index.module.scss
  were-client/src/components/organism/Layout/Header/index.tsx
Labels: enhancement

#73 FEAT: Webtoon Page, WebtoonList Template 구현
  were-client/src/app/layout.tsx
  were-client/src/app/webtoon/page.tsx
  were-client/src/components/molecules/DayFilter/index.module.scss
  were-client/src/components/molecules/DayFilter/index.tsx
  were-client/src/components/molecules/IconText/index.tsx
  were-client/src/components/molecules/NavigationBar/index.tsx
  were-client/src/components/molecules/ScrollTagList/index.module.scss
  were-client/src/components/organism/Layout/Header/index.module.scss
  were-client/src/components/organism/Layout/Header/index.tsx
  were-client/src/components/organism/WebtoonList/index.module.scss
  were-client/src/components/template/WebtoonListTemplate/index.module.scss
  were-client/src/components/template/WebtoonListTemplate/index.tsx
  were-client/src/constant/day.ts
  were-client/src/styles/_base.scss
  were-client/src/util/date.ts
Labels: enhancement

#75 FEAT: Stroage 하단 수정 및 삭제 기능 구현
  were-client/.eslintrc.json
  were-client/package.json
  were-client/public/assets/delete.svg
  were-client/public/assets/deleteHover.svg
  were-client/public/assets/index.ts
  were-client/src/components/atoms/IconButton/index.tsx
  were-client/src/components/molecules/StorageWebtoonInfo/index.tsx
  were-client/src/components/organism/ModifyStorageWebtoonList/draggableItem.tsx
  were-client/src/components/organism/ModifyStorageWebtoonList/index.module.scss
  were-client/src/components/organism/ModifyStorageWebtoonList/index.tsx
  were-client/src/components/organism/StorageWebtoonInfoList/index.module.scss
  were-client/src/components/organism/StorageWebtoonInfoList/index.tsx
Labels: enhancement

#76 FEAT: WebtoonInfoPage 구현 ( Template 도 ) & StorageListModal 컴포넌트 구현
  were-client/src/app/layout.tsx
  were-client/src/app/webtoon/info/list/page.tsx
  were-client/src/components/molecules/StorageListItem/index.module.scss
  were-client/src/components/molecules/StorageListItem/index.tsx
  were-client/src/components/molecules/TagList/index.tsx
  were-client/src/components/molecules/WebtoonInfoUserItems/index.module.scss
  were-client/src/components/molecules/WebtoonInfoUserItems/index.tsx
  were-client/src/components/organism/StorageListModal/index.module.scss
  were-client/src/components/organism/StorageListModal/index.tsx
  were-client/src/components/organism/StorageListModal/useStorageListModal.ts
  were-client/src/components/organism/WebtoonInfo/index.module.scss
  were-client/src/components/template/WebtoonInfoTemplate/index.module.scss
  were-client/src/components/template/WebtoonInfoTemplate/index.tsx
  were-client/src/components/template/WebtoonListTemplate/index.module.scss
  were-client/src/components/template/WebtoonListTemplate/index.tsx
  were-client/src/styles/mixins/_flexbox.scss
  were-client/src/styles/mixins/_index.scss
  were-client/src/styles/variables.scss
Labels: enhancement

#78 FEAT: Login Page 구현
  were-client/package.json
  were-client/public/assets/index.ts
  were-client/public/assets/social-login/btn_gmail.svg
  were-client/public/assets/social-login/btn_kakao.svg
  were-client/public/assets/social-login/btn_naver.svg
  were-client/public/images/login-background.png
  were-client/src/app/LayoutProvider.tsx
  were-client/src/app/layout.tsx
  were-client/src/app/login/page.tsx
  were-client/src/components/atoms/LoginInput/index.module.scss
  were-client/src/components/atoms/LoginInput/index.tsx
  were-client/src/components/molecules/SocialLogins/index.module.scss
  were-client/src/components/molecules/SocialLogins/index.tsx
  were-client/src/components/organism/LoginForm/index.module.scss
  were-client/src/components/organism/LoginForm/index.tsx
  were-client/src/components/template/LoginTemplate/index.module.scss
  were-client/src/components/template/LoginTemplate/index.tsx
Labels: enhancement

#80 FEAT: Storage 상단 수정 기능 구현
  were-client/src/components/molecules/ModifyStorageInfo/index.module.scss
  were-client/src/components/molecules/ModifyStorageInfo/index.tsx
Labels: enhancement

#82 FEAT: Storage Info Page 구현
  were-client/src/app/storage/info/list/page.tsx
  were-client/src/components/molecules/ModifyStorageInfo/index.module.scss
  were-client/src/components/molecules/ModifyStorageInfo/index.tsx
  were-client/src/components/molecules/StorageInfo/index.module.scss
  were-client/src/components/molecules/StorageInfo/index.tsx
  were-client/src/components/molecules/StorageWebtoonInfo/index.module.scss
  were-client/src/components/molecules/StorageWebtoonInfo/index.tsx
  were-client/src/components/organism/ModifyStorageWebtoonList/index.module.scss
  were-client/src/components/organism/ModifyStorageWebtoonList/index.tsx
  were-client/src/components/organism/StorageWebtoonInfoList/index.module.scss
  were-client/src/components/organism/StorageWebtoonInfoList/index.tsx
  were-client/src/components/template/StorageInfoTemplate/index.module.scss
  were-client/src/components/template/StorageInfoTemplate/index.tsx
Labels: enhancement

#84 FEAT: Collection Component 구현
  were-client/src/app/collection/page.tsx
  were-client/src/components/molecules/CollectionCategory/index.module.scss
  were-client/src/components/molecules/CollectionCategory/index.tsx
  were-client/src/components/organism/CollectionContent/index.module.scss
  were-client/src/components/organism/CollectionContent/index.tsx
  were-client/src/components/template/CollectionTemplate/index.module.scss
  were-client/src/components/template/CollectionTemplate/index.tsx
Labels: enhancement, fix
